/* auth */

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/* narratives */

export const RECEIVE_NARRATIVE_PREVIEWS = 'RECEIVE_NARRATIVE_PREVIEWS';
export const RECEIVE_NARRATIVE = 'RECEIVE_NARRATIVE';

/* parties */

export const RECEIVE_PARTY = 'RECEIVE_PARTY';
export const RECEIVE_PARTY_MEMBERS = 'RECEIVE_PARTY_MEMBERS';
export const RECEIVE_PARTY_CHARACTERS = 'RECEIVE_PARTY_CHARACTERS';
export const RECEIVE_PARTY_ROUNDS = 'RECEIVE_PARTY_ROUNDS';
export const ADVANCE_TO_ROUND = 'ADVANCE_TO_ROUND';
export const SET_CURRENT_PARTY = 'SET_CURRENT_PARTY';

/* ux */

export const SET_NOTICE = 'SET_NOTICE';
export const CLEAR_NOTICE = 'CLEAR_NOTICE';

/* reset */

export const RESET_PARTY = 'RESET_PARTY';
export const RESET = 'RESET';
